django_l4_learning_templates/basic_app/urls.py
# from django.conf.urls import url, include
from django.urls import path
from basic_app import views

#Template tagging
app_name = 'basic_app'

urlpatterns=[
    # url(r'^$',views.index,name='index'),
    # url(r'^other/$',views.other,name='other'),
    # url(r'^relative/$',views.relative,name='relative'),
    path('',views.index,name='index'),
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

django_l4_learning_templates/django_l4_learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views,urls

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

django_l4_learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

django_l4_learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100,'Name':'Shanmukha'}
    return render(request,'basic_app/index.html',context=context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

django_l4_learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base File</title>
</head>
<body>
    <nav class='navbar navbar-default navbar-static-top'>
        <div class='container'>
            <ul class='nav navbar-nav'>
                <li><a class='navbar-brand' href="{% url 'index' %}">Brand</a></li>
                <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class='navbar-link' href="{% url 'basic_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class='container'>
        {% block body_block %}
        <!-- Anything outside of this will be inherited when you extend -->
        {% endblock %}
    </div>
</body>
</html>

django_l4_learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load my_custom_templates %}
{% block body_block %}
<h1>Welcome to the Home Page of the level 4 project's basic app </h1>
<h2>{{ text|cut_me:'hello'}}
{{ number|add:'99' }}
{{ Name }}</h2>
{% endblock %}

django_l4_learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>Welcome to the Other page</h1>
<h2>This is an example of template inheritance</h2>
{% endblock %}

django_l4_learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<!-- {% load staticfiles %} -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Relative URL HTML</title>
</head>
<body>
    <h1>This file has the relative URLs of the project</h1>
    <a href="{% url 'basic_app:other' %}">This is the link for the other page</a>
    <a href="{% url 'admin:index' %}">This is the link for admin page</a>
    <a href="{% url 'index' %}">Link to Home Page</a>
</body>
</html>